---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podtato-flux-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./delivery/chart
      sourceRef:
        kind: GitRepository
        name: podtato-flux-repo
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: podtato-flux
  values:
    main:
      serviceType: NodePort

